Change KPP tolerance values for tropchem simulations
Melissa Sulprizio wrote:

   Katie Travis discovered an issue starting with v11-02d when the halogen
   chemistry updates were introduced. When running 2x2.5 tropchem simulations
   for an extended period (usually a month will do), GEOS-Chem crashes with
   a KPP integrator error. This happens for both GEOS-FP and MERRA-2 met
   fields. We don’t seem to encounter these errors for 2x2.5 standard (i.e.
   UCX-based) simulations. I’m wondering if we need to change the tolerance
   values in v11-02? Right now, in flexchem_mod.F we have:

   !%%%%% CONVERGENCE CRITERIA %%%%%

   ! Absolute tolerance
   ATOL      = 1e-2_dp

   ! Relative tolerance
   IF ( Input_Opt%LUCX  ) THEN
      ! UCX-based mechanisms
      !RTOL      = 2e-2_dp
      !RTOL      = 1e-2_dp
      RTOL      = 0.5e-2_dp
   ELSE
      ! Non-UCX mechanisms
      RTOL      = 2e-1_dp
   ENDIF

   I ran two simulations to see if we can resolve the issue in the 2x2.5
   tropchem simulations. In the first simulation I changed the convergence
   criteria (RTOL) to 1e-1_dp following Mat's suggestion and in the second
   I changed the value to 1e-2_dp. In both simulations, we still get the
   integrator errors (Forced exit from Rosenbrock due to the following
   error: Step size too small...) but the 1-month runs finish successfully
   because the error is not encountered twice for a given grid box in a
   given timestep. Also, comparing the two simulations, we see the
   integrator errors at different times and for different grid boxes.

Mat Evans wrote:

   So even if we set the tolerance to be 1e-2_dp we still get a convergence
   error. Its hard to know what to advise here. It sounds like we need a
   bit of work to be done looking at this and looking at the situation that
   the convergence fails and to get an understanding of when we get the
   problem. However given the pressure at the moment to get v11.2 done I
   think my advise would be for us to move to using 1e-2 in the interim and
   we come back to this.

   The major problem I can see from this is in the run time. I don’t know
   how much longer the simulation is to run with this as the convergence
   criteria.

Signed-off-by: Melissa Sulprizio <mpayer@seas.harvard.edu>